### PR TITLE
Remove ondrejmirtes/better-reflection from dependencies

### PR DESCRIPTION
**Pull request by dmytro-dymarchuk**
- Developer(s): @dmytro-dymarchuk 

- Ticket: https://spryker.atlassian.net/browse/TE-10992

- Release Group: https://release.spryker.com/release-groups/view/4090

- merge: merge

#### Release Table

   Module                | Release Type         | Constraint Updates         |
   :--------------------- | :------------------------ | :--------------------- |
   SprykGui   | patch (currently 0.x)  |                       |

-----------------------------------------

##### Change log

Improvements

- Removed `ondrejmirtes/better-reflection` from dependencies.

### CODE REVIEW

**Review by dereuromark — APPROVED** [review]

**Comment by dereuromark** [comment]
Template needed

**Comment by dereuromark** [comment]
Why does this module need this dependency in the first place?

**Comment by dmytro-dymarchuk** [comment]
> Why does this module need this dependency in the first place?

I didn't check. I just believed in the properness of composer.json.

**Comment by dereuromark** [comment]
Maybe we should
It is expensive to have to maintain such dependency updates across multiple repos

**Review by dereuromark — APPROVED** [review]

**Pull request merged**
