### PR TITLE
DT-829: updated license

### PR DESCRIPTION
**Pull request by zyuzka**
Ticket: https://spryker.atlassian.net/browse/DT-829

### CODE REVIEW

**Comment by dereuromark** [comment]
Make sure composer.json and .license files are also properly adjusted!

**Comment by zyuzka** [comment]
> ser.json and .license files are also properly adjusted!

composer.json have:
`"license": "proprietary",`

.license doesn't exist in sprykGui

**Comment by dereuromark** [comment]
But it should exist. How else would all file headers be correct?

**Comment by zyuzka** [comment]
> But it should exist. How else would all file headers be correct?
> Please check that they dont contain the word "suite".

https://github.com/spryker-sdk/spryk-gui/pull/6 - added

**Pull request merged**
