### PR TITLE
TE-1877 Updated constraints to spryk to allow next majors.

### PR DESCRIPTION
**Pull request by stereomon**
- Developer(s): @stereomon

- Ticket: https://spryker.atlassian.net/browse/TE-1877

- Academy PR: ACADEMY_URL_HERE

- Release Group: URL_HERE

#### Please confirm

- [ ] No new OS components - or they have been approved by legal department

#### Documentation

- [ ] Functional documentation provided or in progress?
- [ ] Integration guide for projects provided or not needed?
- [ ] Migration guides for all contained majors provided or not needed?

#### Release Table

   Module                | Release Type         | Constraint Updates         |
   :--------------------- | :------------------------ | :--------------------- |
   SprykGui              | patch (currently 0.x)  |                       |

#### Release Notes

Updated constraints to `spryker-sdk/spryk` which allows the installation of the next majors.

-----------------------------------------

##### Change log

Bugfixes

- Allo next majors of `spryker-sdk/spryk`.

### CODE REVIEW

**Comment by dereuromark** [comment]
We dont major in Spryk. This can be closed.

**Comment by stereomon** [comment]
Aren't e.g. 0.1 to 0.2 updates majors?

**Comment by dereuromark** [comment]
All changes in Spryk seem patches!

**Comment by stereomon** [comment]
IMO every new spryk and there are new ones are minors

**Comment by dereuromark** [comment]
No, they are patches, as those are the "minors" for 0.x versions.

**Pull request closed without merging**
